### ISSUE TITLE
Support SideEffect task that does not need any existing task.

### ISSUE THREAD

**Issue by mchen07** [linkedin/parseq#192] opened 2018-07-26 20:42 UTC
Currently, to fire and forget an async task that does not depend on any existing task, people are implementing this by using the ParSeq interface to return a Task.action that does nothing, and appending a side effect to it in order to spin off a thread that will by executed asynchronously.

We could improve API and provide Task.withSideEffect() that does not need any existing tasks to avoid boilerplate so:
 
Task.action(() -> { }).withSideEffect(response ->
 
Would become:
 
Task.withSideEffect(response ->

**Comment by jodzga** [comment] 2018-07-26 21:21
This is a duplicate of #132

**Closed** 2018-07-26 21:43 UTC
